### ISSUE TITLE
Add save() method to EmbeddingModule.save() to save a embedding_file

### ISSUE THREAD

**Issue by HiromuHota** [SenWu/emmental#49]
**Is your feature request related to a problem? Please describe.**

When you do training and test on two different machines, you have to transfer what's trained from one to another.
As described in https://github.com/HazyResearch/fonduer/blob/master/CHANGELOG.rst

```
# Collect word counter from candidates which is used in LSTM model.
word_counter = collect_word_counter(train_cands)

# Generate word embedding module for LSTM.
emb_layer = EmbeddingModule(
    word_counter=word_counter, word_dim=300, specials=special_tokens
)

...

# Create test dataloader to do prediction.
# Build test dataloader
test_dataloader = EmmentalDataLoader(
    task_to_label_dict={ATTRIBUTE: "labels"},
    dataset=FonduerDataset(
        ATTRIBUTE, test_cands[0], F_test[0], emb_layer.word2id, 2
    ),
    split="test",
    batch_size=100,
    shuffle=False,
)
```

`emb_layer` is trained using train_cands and is used later for test_dataloader.
While EmbeddingModule can **load** embedding_file in `__init__`, it does not have a **save** method to persist what's learnt.

**Describe the solution you'd like**

Add save() method to EmbeddingModule.save() to save a embedding_file.

**Describe alternatives you've considered**

Let me know if you have a better idea.

**Additional context**

**Comment by HiromuHota** [comment]
As I can pickle `emb_layer` and unpickle it, please consider this feature request as a suggestion.

**Comment by SenWu** [comment]
Good point!

Emmental's save model only saves the state_dict of all nn.Module which contains the learned embedding weights.

While if you want to use the model in a different machine or some other cases, you need save the `emb_layer.word2id` to make sure the word index is same as the one used in model training or save the `emb_layer` separately.

Sen

**Comment by HiromuHota** [comment]
Thanks for your answer.
