### ISSUE TITLE
EmmentalModel is not fully saved

### ISSUE THREAD

**Issue by HiromuHota** [SenWu/emmental#50]
**Describe the bug**

When you do training and test on two different machines, you have to transfer what's trained from one to another.
I cannot fully save an EmmentalModel, maybe because 69081680077ba12044c65fe434ee8fae96d6a871 commented out lines that persist variables like `task_names`.
As a result, a KeyError happens when you do a prediction using a loaded model.

> File \"/Users/hiromu/miniconda3/envs/fonduer-mlflow/lib/python3.7/site-packages/emmental/model.py\", line 213, in flow
    for action in self.task_flows[task_name]:
KeyError: 'wiki'

**To Reproduce**
1. Train an EmmentalModel
```
ATTRIBUTE = "wiki"
tasks = create_task(
    ATTRIBUTE, 2, F_train[0].shape[1], 2, emb_layer, model="LogisticRegression"
)

model = EmmentalModel(name=f"{ATTRIBUTE}_task")

for task in tasks:
    model.add_task(task)

emmental_learner = EmmentalLearner()
emmental_learner.learn(model, [train_dataloader])
```
2. Save the model
```
model.save(model_path="model.pkl")
```
3. Load the model
```
model = EmmentalModel()
model.load(model_path="model.pkl")
```
4. Predict using the model
```
model.predict(test_dataloader, return_preds=True)
```

**Expected behavior**

**Error Logs/Screenshots**
If applicable, add error logs or screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Emmental Version: 0.0.4
- Fonduer Version: 0.8.0-dev (ace413d0a687f8e9aa817389c8576d77c02baa59)

**Additional context**

**Comment by SenWu** [comment]
Hi @HiromuHota,

This is a good question!

Emmental only saves state_dict of the model which is the recommended method for saving models in pytorch (https://pytorch.org/tutorials/beginner/saving_loading_models.html) and is a transferable way to use the saved model across machines.

To answer your question, you just need to recreate the model with tasks and then load the model from your checkpoint, here is an example:

```
# Recreate the model

ATTRIBUTE = "wiki"
tasks = create_task(
    ATTRIBUTE, 2, F_train[0].shape[1], 2, emb_layer, model="LogisticRegression"
)

model = EmmentalModel(name=f"{ATTRIBUTE}_task")

for task in tasks:
    model.add_task(task)

# Load the model
model.load(model_path="model.pkl")

# Predict using the pre-trained model
model.predict(test_dataloader, return_preds=True)
```

Hope this can help you better understand/use Emmental.

Sen

**Comment by HiromuHota** [comment]
Thanks for your answer.
Your solution worked, but I ended up saving/loading the entire model (instead of only state_dict (recommended)) just because of its simplicity.

**Comment by SenWu** [comment]
One thing you need to take a care is that saving the entire model will also save the machine Information like how many GPUs are using, data parallel information which might cause extra error in the future. Of course if your machines are identical, you should be fine.

**Comment by HiromuHota** [comment]
This does not affect me immediately, but might cause a trouble in the future.
Thanks for the advice.
